# Generated by Django 5.0.2 on 2025-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_options_remove_curso_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='precio',
            field=models.PositiveIntegerField(help_text='Precio en pesos chilenos'),
        ),
    ]
