# Generated by Django 5.1.7 on 2025-04-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.RenameField(
            model_name='mensajecontacto',
            old_name='fecha_creacion',
            new_name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='mensajecontacto',
            name='leido',
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
    ]
