# Generated by Django 5.0.2 on 2025-05-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente')], default='estudiante', max_length=20),
        ),
    ]
